# Generated by Django 4.1.1 on 2022-10-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_category_image_alter_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
