# Generated by Django 4.1.1 on 2022-10-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
