# Generated by Django 4.1.1 on 2022-10-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cart_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
