# Generated by Django 4.1.1 on 2022-10-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
