# Generated by Django 4.1.1 on 2022-10-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
