# Generated by Django 4.1.1 on 2022-10-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_tax',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
