# Generated by Django 4.1.1 on 2022-10-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_cart_cart_price_alter_cart_cart_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
